### ISSUE TITLE
TeukolskyRadial[s, l, m, a, omega] fails to work with a specific input

### ISSUE THREAD

**Issue by maorby** [BlackHolePerturbationToolkit/Teukolsky#39] opened 2023-07-04 20:11 UTC
The TeukolskyRadial[s, l, m, a, omega] function encounters an error when attempting to calculate the Teukolsky Radial equation for a specific set of input parameters. The parameters causing the issue are as follows:
m = 2
a = 0.8
omega = 0.5
The error message indicates that an infinity expression has been encountered.

**Comment by znasipak** [comment] 2023-07-05 07:12
Have you tried evaluating the function by increasing the precision of these parameters? Infinities can arise when precision is lost in the Teukolsky calculation. For example, running
```
TeukolskyRadial[-2, 2, 2, 0.5`16, 0.8`16]["Up"][10]
```
leads to infinite expressions, but running
```
TeukolskyRadial[-2, 2, 2, 0.5`40, 0.8`40]["Up"][10]
```
does not.

**Comment by maorby** [comment] 2023-07-05 10:41
Yes, I attempted to increase the precision parameters. The desired output parameters are the Reflection and Incidence Amplitudes. However, when I tried running the function with the input values
`TeukolskyRadial[2, 2, 2, 0.840, 0.540]`
It resulted in infinite expressions and failed to calculate the amplitudes. I also tried changing the values of s and l, but the function still encountered infinite expressions.

**Comment by znasipak** [comment] 2023-07-05 13:03
Evaluating `TeukolskyRadial[2, 2, 2, 0.840`30, 0.540`30]` gives me finite results.

**Comment by barrywardell** [comment] 2023-07-05 13:08
I suggest trying with version 1.0.0, which has just now been released. I also am unable to reproduce the original problem.

**Comment by maorby** [comment] 2023-07-05 17:38
> Evaluating `` TeukolskyRadial[2, 2, 2, 0.840`30, 0.540`30] `` gives me finite results.

Yes that's right, for these values it works well.

Sorry for the confusion but the problematic values are:

```
TeukolskyRadial[2, 2, 2, 0.8`30, 0.5`30]
```

**Comment by barrywardell** [comment] 2023-07-06 12:39
I've tracked this down to Eq. (165) of Sasaki & Tagoshi's Living Review. There is a term $\Gamma(1-s+2i\epsilon_+)$. For your specific parameters $\epsilon_+ = 0$ so this is not defined for s>0. I'm not sure what the correct thing to do is in this case.

**Comment by barrywardell** [comment] 2023-07-22 11:44
The error messages were removed in commit 36deb91 and we now return Indeterminate for the relevant amplitudes. I'm closing this issue now as I think this is the best we can do. If a better alternative arises we can reopen this issue.

**Closed by barrywardell** 2023-07-22 11:44 UTC
